### ISSUE TITLE
Add two buttons to the homepage for developer and employer accounts.

### ISSUE THREAD

**Issue by matoval** [GoodStartDev/GoodStart.dev#14]
Add buttons to the index.html to link to developer and employer accounts.
These should stand out and be different than the other page buttons.

**Comment by NickBurness** [comment]
happy to take this on, Am I right in assuming these buttons are to be within the middle of the window instead of the top navigation?

**Comment by matoval** [comment]
It should be on the header but separated from the main nav buttons.
