### ISSUE TITLE
Add a member account page

### ISSUE THREAD

**Issue by matoval** [GoodStartDev/GoodStart.dev#17]
Build a new page that is the page that members land on when they login. It should allow for changing of account info, adding a profile, adding all relevant links, adding resume, and of course a delete account button.

**Comment by sanjaypradeep** [comment]
@matoval I hope, once he/she signs up and on the first successful login, user should get this page, in which it asks about the profile info and addition of relevant links (like LinkedIn/Twitter/Indeed etc).
