### ISSUE TITLE
Collaboration Guidelines

### ISSUE THREAD

**Issue by pablowbk** [GoodStartDev/GoodStart.dev#18]
Adding a new page: 

    Add an issue for the page mockup.
    Submit a mockup to the issue.
    Once mockup is accepted add an issue to build the new page following the mockup.
    Assign issue to contributor or multiple contributor (splitting up the issue between multiple contributors).
    Push new page as a new branch.
    Add a pull request for the added page.
    Accept pull request.
    Merge new page branch with dev branch.

**Comment by kzollove** [comment]
@pablowbk what do you mean by mockup? Like a written proposal or a visual design? How do you make one?

**Comment by pablowbk** [comment]
Either one would work as long as it conveys your idea. You could use Google Docs, open an Issue in the GitHub Repo, créate a Design with Figma/AdobeXD/pen and paper, etc Pablo Weisbekgithub.com/pablowbktwitter.com/wbkpablo De: kzolloveEnviado: Saturday, December 7, 2019 8:41 PMPara: CCWebDevJobBoard/JobBoardCC: Pablo; MentionAsunto: Re: [CCWebDevJobBoard/JobBoard] Collaboration Guidelines (#18) @pablowbk what do you mean by mockup? Like a written proposal or a visual design? How do you make one?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by shivenigma** [comment]
What kind of help is needed here?
