### ISSUE TITLE
Build sign up page

### ISSUE THREAD

**Issue by matoval** [GoodStartDev/GoodStart.dev#33]
Build the sign up page following the mock up that's attached, the Contributors Guidelines, and the style guide. The guidelines can be found in the readMe.
![Sign Up](https://user-images.githubusercontent.com/53712446/70392640-f0905100-1996-11ea-8790-f59a5bb80808.png)

**Comment by shivenigma** [comment]
I can do this.

**Comment by matoval** [comment]
Awesome! I'll assign this issue to you.

**Comment by agiratech-vigneshm** [comment]
If nothing else, I think we can close this. I understand you are busy on lot of things, Just wanted to keep things organized.

**Comment by matoval** [comment]
Thank you for reminding me. I'll close it.
