### ISSUE TITLE
Choose a name for the Job Board. Add name suggestions and vote on names.

### ISSUE THREAD

**Issue by matoval** [GoodStartDev/GoodStart.dev#4]
The name is just a placeholder, what would be a good name?

**Comment by pablowbk** [comment]
something along the lines of:
CodeNewbies Board
Juniors JobBoard
Start Here
NewbieHub
The Hub
Job-O-rama????

haha I'm not good with names. Tried to come up with a pun , but failed.

**Comment by matoval** [comment]
Thanks for the suggestion. Maybe we should have a poll where we all can add different name suggestion and vote on them?

**Comment by pablowbk** [comment]
yes!

**Comment by sanjaypradeep** [comment]
@matoval Create a poll in slack. All members in the group could be aware of, can come with new suggestions.

**Comment by nasimuddin01** [comment]
Name is selected. GoodStart.DEV
