### ISSUE TITLE
Design a logo for the new name GoodStart.dev

### ISSUE THREAD

**Issue by matoval** [GoodStartDev/GoodStart.dev#45]
We need a logo designed for the new name GoodStart.dev

**Comment by nasimuddin01** [comment]
![logo-final](https://user-images.githubusercontent.com/47916033/70890571-97b45e80-200f-11ea-8e9c-0f1502aebcfd.png)

Here is the logo

**Comment by nasimuddin01** [comment]
When use this logo for website use svg file.. Which can be exported from here. 
https://www.figma.com/file/t5M2kkW2m5NIbmfMD4lr5A/CCJobBoard?node-id=134%3A146
